image: python:latest

pages:
  script:
  - pip install scipy
  - pip install numpy
  - pip install sphinx
  - cd docs
  - make html
  - mv ./build/html/ ../public/
  tags:
  - docker
  artifacts:
    paths:
    - public
  only:
  - master

test:
  script:
  - apt-get install swig
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py develop
  - python -m pytest --cov
##  - python -m pytest --doctest-modules --cov
  tags:
  - docker
  only:
  - master
