##image: alpine

##image: python:latest
image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add make
  - cd docs
  - make html
  - mv build/html/ ../public/
  tags:
  - docker
  artifacts:
    paths:
    - public
  only:
  - master

##before_script:
##  - python -V

##test:
##  script:
##  - pip install -r requirements.txt
##  - python -m pytest --doctest-modules --cov
##  tags:
##  - docker
