image: python:latest

pages:
  script:
  - pip install scipy
  - pip install numpy
  - pip install sphinx
  - cd docs
  - make html
  - mv ./build/html/ ../public/
  tags:
  - docker
  artifacts:
    paths:
    - public
  only:
  - master

build:
  script:
  - cd ..
  - git clone https://github.com/swig/swig.git
  - cd swig
  - ./autogen.sh && ./configure && make
  - cd ../planar_python_robotics
  - pip install -r requirements.txt
  - python setup.py build
  tags:
  - docker
  only:
  - master

test:
  script:
  - pip install -r requirements.txt
  - python setup.py install
  - python -m pytest --cov
  tags:
  - docker
  only:
  - master
